version: "3.10"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    env_file:
      - ./server/.env

    ports:
      - "8000:8000"

    volumes:
      - ./server:/app/backend
