name: Deploy Django to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd server
          docker build -t my-django-app:latest .
          docker tag my-django-app:latest ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

      - name: Prepare EC2 Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Docker Compose file to EC2
        run: |
          echo "${{ secrets.DOCKER_COMPOSE_FILE }}" > docker-compose.yml
          scp -o StrictHostKeyChecking=no -i ec2_key.pem docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker-compose down
          docker-compose pull
          docker-compose up -d
          EOF
